name: nbt

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'

    - name: Compile package
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'

    - name: Test with coverage
      run: go test -v ./... -coverprofile="coverage.out"

    - name: Format coverage report
      run: go tool cover -html "coverage.out" -o "coverage.html"

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: ./coverage.html
        
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
        
      - name: Lint code
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --config=./.github/linter/.golangci.yml --verbose
          